name: CI
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v11
      with:
        nix_path: nixpkgs=channel:nixos-20.09-small
    - uses: actions/checkout@v2
    - run: make test
